# Generated by Django 5.2.11 on 2026-02-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0002_patient_reviewed_at_patient_reviewed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number_next_of_kin',
            field=models.CharField(max_length=20),
        ),
    ]
